### Register User
POST http://localhost:8080/Authentication/Register
Content-Type: application/json

{
  "firstname": "Le",
  "lastname": "Dung",
  "email": "vandung@gmail.com",
  "password": "1234",
  "role": "ADMIN"
}

> {% client.global.set("auth-token", response.body.token); %}

### Query Demo endpoint
GET http://localhost:8080/Authentication/Demo
Authorization: Bearer {{auth-token}}

### Change the password
PATCH http://localhost:8080/User
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "1234",
  "newPassword": "newpass",
  "confirmPassword": "newpass"
}

### Login again and update the token
POST http://localhost:8080/Authentication/Authenticate
Content-Type: application/json

{
  "email": "vandung@gmail.com",
  "password": "newpass"
}

> {% client.global.set("new-auth-token", response.body.token); %}

### Query the endpoint after password change
GET http://localhost:8080/Authentication/Demo
Authorization: Bearer {{new-auth-token}}
